package com.hazelcast.platform.training.cloud.client;

import java.util.Properties;

import com.hazelcast.client.config.ClientConfig;
import com.hazelcast.client.spi.properties.ClientProperty;
import com.hazelcast.config.GroupConfig;
import com.hazelcast.config.SSLConfig;

public class Utils {

	//TODO: Set your cluster name here...
	public static String CLOUD_CLUSTER_NAME = "MY_CLOUD_SERVICE_CLUSTER_NAME";
	
    public  static ClientConfig getCloudClientConfig() {
		ClientConfig cloudClientConfig = null;
		try {
	        ClassLoader classLoader = Utils.class.getClassLoader();
	        Properties props = new Properties();
	        
	        //TODO: Sign up for cloud starter and create a cluster. Simply cut & paste from java client code 
	        //      generated by the cloud service, set the name of your client 'TrainingCloudClinet'.
	        //      If you choose encryption, copy the security store files to the  project resource directory. 

		}catch(Throwable t) {
			t.printStackTrace();
		}
        return cloudClientConfig;
    }	
}
